### PR TITLE
Fix: DCQL Credential matching for some common jwt claims

### LINKED ISSUE #318: DCQL Query for `iss`
When an DCQL Query requests a specific value for `iss`, our implementation can't even show the consent screen for it. 

I think the problem is, that for `DCQLJsonClaimsQuery.executeJsonClaimsQueryAgainstCredential()` the passed in `credentialStructureExtractor` is in essence the value of `ConstantIndex.CredentialScheme.toJsonElement()`, and there we're only adding the claim names (and complex structures) of the scheme. So this does not include the [other JWT claims](https://www.ietf.org/archive/id/draft-ietf-oauth-sd-jwt-vc-09.html#section-3.2.2) of the credential itself.

https://github.com/a-sit-plus/valera/pull/304 plays into this as well, as we should be able to at least present the consent screen to the user, without filtering for actual values in our credentials.

See also https://github.com/a-sit-plus/vck/pull/321 and https://github.com/a-sit-plus/valera/pull/317

Example query:
```json
  "dcql_query": {
    "credential_sets": [
      {
        "purpose": "To obtain e-prescription, we need to verify your identity.",
        "options": [
          [
            "pid_sd_jwt",
          ]
        ]
      }
    ],
    "credentials": [
      {
        "id": "pid_sd_jwt",
        "format": "vc+sd-jwt",
        "meta": {
          "vct_values": [
            "urn:eu.europa.ec.eudi:pid:1"
          ]
        },
        "claims": [
          {
            "path": [
              "given_name"
            ]
          },
          {
            "path": [
              "family_name"
            ]
          },
          {
            "path": [
              "iss"
            ],
            "values": [
              "https://wallet.a-sit.at/m6"
            ]
          }
        ]
      }
    ]
  },
````

### PR DESCRIPTION
**Pull request by acrusage-iaik**
Hopefully fixes #318

### CODE REVIEW

File: shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/Extensions.kt [hunk 1]
```diff
@@ -232,6 +272,7 @@ fun ConstantIndex.CredentialScheme.toJsonElement(
         }
 
         is CompanyRegistrationScheme -> buildJsonObject {
+            addRepresentationSpecificDummyMetadata(representation)
```
Comment (nodh) [inline shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/Extensions.kt:275]: wouldn't this better be placed into the return statement, as there `vct` is already being added?

File: shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/Extensions.kt [hunk 2]
```diff
@@ -297,3 +340,26 @@ fun ConstantIndex.CredentialScheme.toJsonElement(
         }
     }
 }
+
+private fun JsonObjectBuilder.addRepresentationSpecificDummyMetadata(representation: CredentialRepresentation) {
+    when (representation) {
+        PLAIN_JWT -> TODO()
+        SD_JWT -> {
+            put("iss", "")
```
Comment (nodh) [inline shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/Extensions.kt:348]: That list is missing `status` and `cnf` from https://www.ietf.org/archive/id/draft-ietf-oauth-sd-jwt-vc-09.html#name-registered-jwt-claims ... although that's probably not used in a query, but who knows?

File: shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/Extensions.kt [hunk 3]
```diff
@@ -297,3 +340,26 @@ fun ConstantIndex.CredentialScheme.toJsonElement(
...
+            put("nbf", 0)
+            put("iat", 0)
+            put("exp", 0)
+        }
+
+        ISO_MDOC -> TODO()
+    }
+}
+
+private data class DCQLClaimsQueryInstance(
```
[the remark this answers is not in the document]
Comment (acrusage-iaik) [reply shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/Extensions.kt]: fixed

File: shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/Extensions.kt (hunk 1 above)
Comment (acrusage-iaik) [reply shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/Extensions.kt]: fixed

File: shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/Extensions.kt (hunk 2 above)
Comment (acrusage-iaik) [reply shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/Extensions.kt:351]: I'm sure there are other claims missing as well, but I added those two for now

File: shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/Extensions.kt [hunk 4]
```diff
@@ -303,3 +343,20 @@ fun ConstantIndex.CredentialScheme.toJsonElement(
         }
     }
 }
+
+private fun JsonObjectBuilder.addRepresentationSpecificDummyMetadata(representation: CredentialRepresentation) {
+    when (representation) {
```
Comment (nodh) [inline shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/Extensions.kt:348]: Now where this method is called, we are sure it's `SD_JWT`, so the `when` isn't necessary

**Review by nodh — APPROVED** [review]

File: shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/Extensions.kt (hunk 4 above)
Comment (acrusage-iaik) [reply shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/Extensions.kt]: fixed
